mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    #path('', include('polls.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path, include
from . import views
from .views import SignUpView

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('signup/', SignUpView.as_view(template_name='registration/signup.html'), name='signup'),
    #path('', views.IndexView.as_view(), name='index'),
    #Arguments inside brackets should be the same as the expected argument in the method in the second argument of path
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'), 
    path('<int:question_id>/', views.detail, name='detail'),
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

# app_name = 'polls'
# urlpatterns = [
#     path('', views.IndexView.as_view(), name='index'),
#     path('<int:pk>/', views.DetailView.as_view(), name='detail'),
#     path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text
    
class Person(AbstractUser):
    phone_number = models.CharField(max_length=50, null=True, blank=True)

#DEFAULT_PERSON_ID = 2 # For user amaghous
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib import auth
from django.contrib.auth.decorators import login_required
#from django.template import loader

from django import forms


from .models import Question, Choice, Person

'''
The view that manages the Urls 
'''

@login_required
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:3]
    # template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    #output = ', '.join([q.question_text for q in latest_question_list])
    #return HttpResponse(template.render(context, request))
    return render(request, 'polls/index.html', context)
    #return HttpResponse(output)

@login_required
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question, 'question_id': question_id})

@login_required
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    choices = question.choice_set.all()
    choice_list = []
    for choice in choices:
        choice_list.append([choice.choice_text, choice.votes])
        #choice_vote_list.append(choice.votes)
    context = {
        'question_text': question.question_text,
        'choice_list': choice_list,
        #'choice_text_list': choice_text_list,
        #'choice_vote_list': choice_vote_list,
    }

    return render(request, 'polls/results.html', context)

class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Person
        fields = ['username', 'phone_number']

    def save(self, commit=True):
        user = super(SignupForm, self).save(commit=False)
        #user.set_password(user.password) # set password properly before commit
        '''
        The "set_password" method does not properly work with "super(SignupForm, self).save(commit=False)" and the later already hashes the users passwd "set_password" was introduced
        so that we do the hash, so either the doc I used was deprecated or something else.
        '''
        if commit:
            user.save()
        return user

class SignUpView(generic.CreateView):
    form_class = SignupForm
    success_url = reverse_lazy('polls:login')
    template_name = 'registration/signup.html'

@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id, )))

def user_login(request): # each request is related to it's own user
    if request.method == 'POST':
        try:        
            username = request.POST['username']
            password = request.POST['password']
            if Person.objects.filter(username=username).exists():
                user = Person.objects.get(username=username)
            if user.check_password(password):
                user = auth.authenticate(username=username, password=password)
                if user is not None:
                    auth.login(request, user)
                    return redirect('home')
            # else:
            #     print("Password check failed")
            else:
                return redirect('polls:login')
        except Exception as problem:
            print(problem)
            return redirect('polls:login')
    return render(request, 'polls/login.html')

# class IndexView(generic.ListView):
#     template_name = 'polls/index.html'
#     context_object_name = 'latest_question_list'

#     def get_queryset(self):
#         return Question.objects.order_by('-pub_date')[:3]

# class DetailView(generic.DetailView):
#     model = Question
#     template_name = 'polls/detail.html'

# class ResultsView(generic.DetailView):
#     model = Question
#     template_name = 'polls/results.html'

polls/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

polls/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <li>{{user.phone_number}}</li>
  <p><a href="{% url 'logout' %}">Log Out</a></p>
  <p><a href="{% url 'password_change' %}">Change password</a></p>
  {% else %}
  <p>You are not logged in</p>
  <p><a href="{% url 'polls:login' %}">Log In</a></p>
  <p><a href="{% url 'polls:signup' %}">Sign up</a></p>
{% endif %}
{% endblock %}

polls/templates/polls/detail.html
<!-- p>Question ID: {{ question_id }}</p>
<p>Question: {{ question }}</p-->

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/login.html
<!DOCTYPE html>
<html>

<head>
    <title>Login in Polls</title>
</head>
    
<body>
    <form method="POST">
        {% csrf_token %}
        <p>
            <label>Username</label>
            <input type="text" name="username">
        </p>
        <p>
            <label>Password</label>
            <input type="password" name="password">
        </p>
        <button type="submit">Login</button>
    </form>
</body>

</html>



<!-- {% block title %}Login{% endblock %}

{% block content %}
<h2>Log In</h2>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}
  <button type="submit">Log In</button>
</form>
{% endblock %} -->

polls/templates/polls/results.html
<h2>{{question_text}}</h2>

{% if choice_list %}
    <ul>
        {% for choice_text,votes in choice_list %}
            <li>Choice {{choice_text}} got {{votes}} votes</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No choices are available.</p>
{% endif %}